language: julia
os:
  - linux
  - osx
julia:
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("GaussianRandomFields")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
